scan:
name: Scan
needs: [ build ]
runs-on: ubuntu-latest
steps:
- name: Login to Docker Hub
uses: docker/login-action@v2
with:
username: ${{ secrets.DOCKERHUB_LOGIN }}
password: ${{ secrets.DOCKER_HUB_PASSWORD }}
- name: Docker Scout CVEs
uses: docker/scout-action@v1.5.0
with:
command: cves
image: sibunanick/student-app:latest
# only-fixed: true
only-severities: critical,high
ignore-base: false
ignore-unchanged: false
write-comment: true
ignore-cves: CVE-2023-XXXX,CVE-2023-YYYY
github-token: ${{ secrets. GITHUB_TOKEN }} 
exit-code: true
exit-on: vulnerability
